### ISSUE TITLE
isy.py tracebacks for KeyError: 'parent'  & KeyError: 'property'

### ISSUE THREAD

**Issue by ace5657388** [kevinkahn/softconsole#1]
With both release and currentbeta, I have an issue where console.py dies during startup with the following error:

```
Traceback (most recent call last):
  File "console.py", line 83, in <module>
    config.ISY = isy.ISY(config.ISYrequestsession)
  File "/home/pi/beta/softconsole-currentbeta/isy.py", line 220, in __init__
    n = Node(node['@flag'], node['name'], node['address'], int(node['parent']['@type']),
KeyError: 'parent'
```

The cause appears to be my devices located at the root of the device tree, not in a subfolder. , looking at these devices in the raw node tree (using http://isy/rest/nodes/) I see that these nodes are missing the "<parent type="#">#####</parent>" entry.

If I move all devices into subfolders, then diagnostic changes to line 221, with "KeyError: 'property'", and is caused by a ZWave repeater, a device which has no property associated.

**Comment by kevinkahn** [comment]
Good catch on the node at top level - didn't have any of those and it was an oversight.  I have pushed a new currentbeta that I think will fix that.  For the other issue - I don't have any Zwave devices so it is hard to test (:-)).  I didn't think a node could have no properties so what I have done for now is to just skip adding any such nodes to the tree since it sounds like you can't actually do anything with them.  If they do need to be controlled from the console I'll have to get more educated about them.  I am a bit limited at the moment in what I can test since I am remote from my home system and that system had its PLM fail but I think I have made the changes you need.  Give the currentbeta a try and let me know if I got these bugs squashed.
